<script>
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	onMount(async () => {
		if (browser) {
			const Plotly = await import('plotly.js-dist-min');
			if (document.getElementById('f1600c66-a02f-49d4-a132-471bac481428')) {
				Plotly.newPlot(
					'f1600c66-a02f-49d4-a132-471bac481428',
					[
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Neutral',
							marker: { color: '#636efa', pattern: { shape: '' } },
							name: 'Neutral',
							offsetgroup: 'Neutral',
							orientation: 'v',
							showlegend: true,
							x: [
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral',
								'Neutral'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Enjoyment',
							marker: { color: '#EF553B', pattern: { shape: '' } },
							name: 'Enjoyment',
							offsetgroup: 'Enjoyment',
							orientation: 'v',
							showlegend: true,
							x: [
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment',
								'Enjoyment'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Anger',
							marker: { color: '#00cc96', pattern: { shape: '' } },
							name: 'Anger',
							offsetgroup: 'Anger',
							orientation: 'v',
							showlegend: true,
							x: [
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger',
								'Anger'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Sadness',
							marker: { color: '#ab63fa', pattern: { shape: '' } },
							name: 'Sadness',
							offsetgroup: 'Sadness',
							orientation: 'v',
							showlegend: true,
							x: [
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness',
								'Sadness'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Contempt',
							marker: { color: '#FFA15A', pattern: { shape: '' } },
							name: 'Contempt',
							offsetgroup: 'Contempt',
							orientation: 'v',
							showlegend: true,
							x: [
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt',
								'Contempt'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Disgust',
							marker: { color: '#19d3f3', pattern: { shape: '' } },
							name: 'Disgust',
							offsetgroup: 'Disgust',
							orientation: 'v',
							showlegend: true,
							x: [
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust',
								'Disgust'
							],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Surprise',
							marker: { color: '#FF6692', pattern: { shape: '' } },
							name: 'Surprise',
							offsetgroup: 'Surprise',
							orientation: 'v',
							showlegend: true,
							x: ['Surprise', 'Surprise', 'Surprise', 'Surprise'],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						},
						{
							alignmentgroup: 'True',
							bingroup: 'x',
							hovertemplate:
								'tone_AI=%{x}\u003cbr\u003ecount=%{y}\u003cextra\u003e\u003c\u002fextra\u003e',
							legendgroup: 'Fear',
							marker: { color: '#B6E880', pattern: { shape: '' } },
							name: 'Fear',
							offsetgroup: 'Fear',
							orientation: 'v',
							showlegend: true,
							x: ['Fear', 'Fear'],
							xaxis: 'x',
							yaxis: 'y',
							type: 'histogram'
						}
					],
					{
						barmode: 'relative',
						legend: { title: { text: 'tone_AI' }, tracegroupgap: 0 },
						template: {
							data: {
								barpolar: [
									{
										marker: {
											line: { color: 'rgb(17,17,17)', width: 0.5 },
											pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 }
										},
										type: 'barpolar'
									}
								],
								bar: [
									{
										error_x: { color: '#f2f5fa' },
										error_y: { color: '#f2f5fa' },
										marker: {
											line: { color: 'rgb(17,17,17)', width: 0.5 },
											pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 }
										},
										type: 'bar'
									}
								],
								carpet: [
									{
										aaxis: {
											endlinecolor: '#A2B1C6',
											gridcolor: '#506784',
											linecolor: '#506784',
											minorgridcolor: '#506784',
											startlinecolor: '#A2B1C6'
										},
										baxis: {
											endlinecolor: '#A2B1C6',
											gridcolor: '#506784',
											linecolor: '#506784',
											minorgridcolor: '#506784',
											startlinecolor: '#A2B1C6'
										},
										type: 'carpet'
									}
								],
								choropleth: [{ colorbar: { outlinewidth: 0, ticks: '' }, type: 'choropleth' }],
								contourcarpet: [
									{ colorbar: { outlinewidth: 0, ticks: '' }, type: 'contourcarpet' }
								],
								contour: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'contour'
									}
								],
								heatmapgl: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'heatmapgl'
									}
								],
								heatmap: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'heatmap'
									}
								],
								histogram2dcontour: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'histogram2dcontour'
									}
								],
								histogram2d: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'histogram2d'
									}
								],
								histogram: [
									{
										marker: { pattern: { fillmode: 'overlay', size: 10, solidity: 0.2 } },
										type: 'histogram'
									}
								],
								mesh3d: [{ colorbar: { outlinewidth: 0, ticks: '' }, type: 'mesh3d' }],
								parcoords: [
									{ line: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'parcoords' }
								],
								pie: [{ automargin: true, type: 'pie' }],
								scatter3d: [
									{
										line: { colorbar: { outlinewidth: 0, ticks: '' } },
										marker: { colorbar: { outlinewidth: 0, ticks: '' } },
										type: 'scatter3d'
									}
								],
								scattercarpet: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scattercarpet' }
								],
								scattergeo: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scattergeo' }
								],
								scattergl: [{ marker: { line: { color: '#283442' } }, type: 'scattergl' }],
								scattermapbox: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scattermapbox' }
								],
								scatterpolargl: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scatterpolargl' }
								],
								scatterpolar: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scatterpolar' }
								],
								scatter: [{ marker: { line: { color: '#283442' } }, type: 'scatter' }],
								scatterternary: [
									{ marker: { colorbar: { outlinewidth: 0, ticks: '' } }, type: 'scatterternary' }
								],
								surface: [
									{
										colorbar: { outlinewidth: 0, ticks: '' },
										colorscale: [
											[0.0, '#0d0887'],
											[0.1111111111111111, '#46039f'],
											[0.2222222222222222, '#7201a8'],
											[0.3333333333333333, '#9c179e'],
											[0.4444444444444444, '#bd3786'],
											[0.5555555555555556, '#d8576b'],
											[0.6666666666666666, '#ed7953'],
											[0.7777777777777778, '#fb9f3a'],
											[0.8888888888888888, '#fdca26'],
											[1.0, '#f0f921']
										],
										type: 'surface'
									}
								],
								table: [
									{
										cells: { fill: { color: '#506784' }, line: { color: 'rgb(17,17,17)' } },
										header: { fill: { color: '#2a3f5f' }, line: { color: 'rgb(17,17,17)' } },
										type: 'table'
									}
								]
							},
							layout: {
								annotationdefaults: { arrowcolor: '#f2f5fa', arrowhead: 0, arrowwidth: 1 },
								autotypenumbers: 'strict',
								coloraxis: { colorbar: { outlinewidth: 0, ticks: '' } },
								colorscale: {
									diverging: [
										[0, '#8e0152'],
										[0.1, '#c51b7d'],
										[0.2, '#de77ae'],
										[0.3, '#f1b6da'],
										[0.4, '#fde0ef'],
										[0.5, '#f7f7f7'],
										[0.6, '#e6f5d0'],
										[0.7, '#b8e186'],
										[0.8, '#7fbc41'],
										[0.9, '#4d9221'],
										[1, '#276419']
									],
									sequential: [
										[0.0, '#0d0887'],
										[0.1111111111111111, '#46039f'],
										[0.2222222222222222, '#7201a8'],
										[0.3333333333333333, '#9c179e'],
										[0.4444444444444444, '#bd3786'],
										[0.5555555555555556, '#d8576b'],
										[0.6666666666666666, '#ed7953'],
										[0.7777777777777778, '#fb9f3a'],
										[0.8888888888888888, '#fdca26'],
										[1.0, '#f0f921']
									],
									sequentialminus: [
										[0.0, '#0d0887'],
										[0.1111111111111111, '#46039f'],
										[0.2222222222222222, '#7201a8'],
										[0.3333333333333333, '#9c179e'],
										[0.4444444444444444, '#bd3786'],
										[0.5555555555555556, '#d8576b'],
										[0.6666666666666666, '#ed7953'],
										[0.7777777777777778, '#fb9f3a'],
										[0.8888888888888888, '#fdca26'],
										[1.0, '#f0f921']
									]
								},
								colorway: [
									'#636efa',
									'#EF553B',
									'#00cc96',
									'#ab63fa',
									'#FFA15A',
									'#19d3f3',
									'#FF6692',
									'#B6E880',
									'#FF97FF',
									'#FECB52'
								],
								font: { color: '#f2f5fa' },
								geo: {
									bgcolor: 'rgb(17,17,17)',
									lakecolor: 'rgb(17,17,17)',
									landcolor: 'rgb(17,17,17)',
									showlakes: true,
									showland: true,
									subunitcolor: '#506784'
								},
								hoverlabel: { align: 'left' },
								hovermode: 'closest',
								mapbox: { style: 'dark' },
								paper_bgcolor: 'rgb(17,17,17)',
								plot_bgcolor: 'rgb(17,17,17)',
								polar: {
									angularaxis: { gridcolor: '#506784', linecolor: '#506784', ticks: '' },
									bgcolor: 'rgb(17,17,17)',
									radialaxis: { gridcolor: '#506784', linecolor: '#506784', ticks: '' }
								},
								scene: {
									xaxis: {
										backgroundcolor: 'rgb(17,17,17)',
										gridcolor: '#506784',
										gridwidth: 2,
										linecolor: '#506784',
										showbackground: true,
										ticks: '',
										zerolinecolor: '#C8D4E3'
									},
									yaxis: {
										backgroundcolor: 'rgb(17,17,17)',
										gridcolor: '#506784',
										gridwidth: 2,
										linecolor: '#506784',
										showbackground: true,
										ticks: '',
										zerolinecolor: '#C8D4E3'
									},
									zaxis: {
										backgroundcolor: 'rgb(17,17,17)',
										gridcolor: '#506784',
										gridwidth: 2,
										linecolor: '#506784',
										showbackground: true,
										ticks: '',
										zerolinecolor: '#C8D4E3'
									}
								},
								shapedefaults: { line: { color: '#f2f5fa' } },
								sliderdefaults: {
									bgcolor: '#C8D4E3',
									bordercolor: 'rgb(17,17,17)',
									borderwidth: 1,
									tickwidth: 0
								},
								ternary: {
									aaxis: { gridcolor: '#506784', linecolor: '#506784', ticks: '' },
									baxis: { gridcolor: '#506784', linecolor: '#506784', ticks: '' },
									bgcolor: 'rgb(17,17,17)',
									caxis: { gridcolor: '#506784', linecolor: '#506784', ticks: '' }
								},
								title: { x: 0.05 },
								updatemenudefaults: { bgcolor: '#506784', borderwidth: 0 },
								xaxis: {
									automargin: true,
									gridcolor: '#283442',
									linecolor: '#506784',
									ticks: '',
									title: { standoff: 15 },
									zerolinecolor: '#283442',
									zerolinewidth: 2
								},
								yaxis: {
									automargin: true,
									gridcolor: '#283442',
									linecolor: '#506784',
									ticks: '',
									title: { standoff: 15 },
									zerolinecolor: '#283442',
									zerolinewidth: 2
								}
							}
						},
						title: { text: 'Tone' },
						width: 800,
						xaxis: {
							anchor: 'y',
							categoryarray: [
								'Neutral',
								'Enjoyment',
								'Anger',
								'Sadness',
								'Contempt',
								'Disgust',
								'Surprise',
								'Fear'
							],
							categoryorder: 'array',
							domain: [0.0, 1.0],
							title: { text: 'tone_AI' }
						},
						yaxis: { anchor: 'x', domain: [0.0, 1.0], title: { text: 'count' } }
					},
					{ responsive: true }
				);
			}
		}
	});
</script>

<div>
	<div
		id="f1600c66-a02f-49d4-a132-471bac481428"
		class="plotly-graph-div"
		style="width:800px;"
	></div>
</div>
